server:
  port: 8080
  contextPath: /infracommerce
---
spring:
  profiles: local,default
datasource:
  infracommerce:
    url: jdbc:mysql://localhost:3306/infracommerce
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect