server:
  port: 8080
  contextPath: /infracommerce
---
spring:
  profiles: local,default
datasource:
  infracommerce:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop-update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect