server:
  port: 8080
  contextPath: /infracommerce
---
spring:
  profiles: local,default
datasource:
  infracommerce:
    url: us-cdbr-iron-east-03.cleardb.net/heroku_3a474168aa0c33f
    username: b440be76b59cc8
    password: 8b8e1d71
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop-update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect